url: https://www.michaelbamford.com # the base hostname & protocol for your site, e.g. http://example.com
email: michael@michaelbamford.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Michael Bamford"

plugins:
  - jekyll-feed
  - jekyll-heroicons
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tailwind

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "tutorial"

tailwind:
  input: "assets/css/app.css"
  minify: false

heroicons:
  variant: "outline"
  default_class:
    { solid: "size-6", outline: "size-6", mini: "size-5", micro: "size-4" }
